name: Release and Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: ./src
          extra_plugins: |
            @semantic-release/commit-analyzer@v9.0.2
            @semantic-release/release-notes-generator@v10.0.3
            @semantic-release/github@v8.1.0
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        if: steps.release.outputs.new_release_published == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          docker buildx create --use
          docker buildx build -t latebitflip/bulwark.auth:${{ steps.release.outputs.new_release_version }} --platform linux/amd64 --push .
          docker buildx build -t latebitflip/bulwark.auth:${{ steps.release.outputs.new_release_version }}-arm --platform linux/arm64 --push .